# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skull_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_skullUi_3(object):
    def setupUi(self, skullUi_3):
        skullUi_3.setObjectName("skullUi_3")
        skullUi_3.resize(1068, 736)
        self.centralwidget = QtWidgets.QWidget(skullUi_3)
        self.centralwidget.setObjectName("centralwidget")
        self.skullUi = QtWidgets.QLabel(self.centralwidget)
        self.skullUi.setGeometry(QtCore.QRect(-10, -20, 1081, 781))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.skullUi.setFont(font)
        self.skullUi.setMouseTracking(True)
        self.skullUi.setTabletTracking(False)
        self.skullUi.setStyleSheet("border-color: rgb(227, 12, 12);")
        self.skullUi.setText("")
        self.skullUi.setPixmap(QtGui.QPixmap("../../../Downloads/语音音波.gif"))
        self.skullUi.setScaledContents(True)
        self.skullUi.setObjectName("skullUi")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(52, 152, 219 );")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(880, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(52, 152, 219 );\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(800, 40, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n" 
"border-radius:none;\n"
"color: #85C1E9;\n"
"font-size:15px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(800, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color: #85C1E9;\n"
"font-size:15px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 280, 291, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/AlTq.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        skullUi_3.setCentralWidget(self.centralwidget)

        self.retranslateUi(skullUi_3)
        QtCore.QMetaObject.connectSlotsByName(skullUi_3)

    def retranslateUi(self, skullUi_3):
        _translate = QtCore.QCoreApplication.translate
        skullUi_3.setWindowTitle(_translate("skullUi_3", "MainWindow"))
        self.pushButton_2.setText(_translate("skullUi_3", "Run"))
        self.pushButton_3.setText(_translate("skullUi_3", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    skullUi_3 = QtWidgets.QMainWindow()
    ui = Ui_skullUi_3()
    ui.setupUi(skullUi_3)
    skullUi_3.show()
    sys.exit(app.exec_())
